spring:
  server:
    port: 8081
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb # H2 DB 연결 주소 (In-Memory Mode)
    username: sa # H2 DB 접속 ID (사용자 지정)
    password:  # H2 DB 접속 PW (사용자 지정)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true # SQL 쿼리 출력 여부
        format_sql: false # SQL 쿼리 포맷팅 여부
  data:
    redis:
      host: localhost
      port: 6379